version: "3.9"

services:
  btc-transaction-scanner-bot:
    image: btc-transaction-scanner-bot:dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc-transaction-scanner-bot-dev
    env_file:
      - ./.env
    environment:
      - APP_ENV=development
      - LOG_PRETTY=true
      - VERBOSE=${VERBOSE}
      - BTC_RPC_API_URL=${BTC_RPC_API_URL}
      - BITCOIN_POLL_INTERVAL_MS=${BITCOIN_POLL_INTERVAL_MS}
      - RESOLVE_INPUT_ADDRESSES=${RESOLVE_INPUT_ADDRESSES}
      - CUR_CACHE_VALIDITY_PERIOD=${CUR_CACHE_VALIDITY_PERIOD}
      - COINMARKETCAP_BASE_URL=${COINMARKETCAP_BASE_URL}
      - API_KEY_COINMARKETCAP=${API_KEY_COINMARKETCAP}
      - PARSE_RAW_BLOCKS=${PARSE_RAW_BLOCKS}
    volumes:
      - ./:/app
      - /app/node_modules
      - ./cache:/app/cache
      - ./logs:/app/logs
    command: sh -c "bun install && bun --watch src/index.ts"
    restart: unless-stopped

