version: "3.9"

services:
  btc-transaction-scanner-bot:
    image: btc-transaction-scanner-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc-transaction-scanner-bot
    env_file:
      - ./.env
    environment:
      # Allow overriding or setting explicitly in compose if needed
      - APP_ENV=production
      - BTC_RPC_API_URL=${BTC_RPC_API_URL}
      - BITCOIN_POLL_INTERVAL_MS=${BITCOIN_POLL_INTERVAL_MS}
      - RESOLVE_INPUT_ADDRESSES=${RESOLVE_INPUT_ADDRESSES}
      - CUR_CACHE_VALIDITY_PERIOD=${CUR_CACHE_VALIDITY_PERIOD}
      - API_KEY_COINMARKETCAP=${API_KEY_COINMARKETCAP}
      - PARSE_RAW_BLOCKS=${PARSE_RAW_BLOCKS}
    volumes:
      - ./addresses.json:/app/addresses.json:ro
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped

